apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: ci-pipeline
spec:
  params:
    - name: redhat-base-image
      type: string
      default: registry.access.redhat.com/ubi9/ubi:latest
      description: Base image from Red Hat UBI
    - name: python
      type: string
      default: registry.access.redhat.com/ubi9/python-311
      description: Python image from Red Hat UBI
    - name: repository-url
      type: string
      description: The git repository URL
    - name: revision
      type: string
      description: The git revision (branch, tag, sha)
    - name: ref
      type: string
      description: The git ref (e.g., refs/heads/main)
    - name: event-type
      type: string
      description: The event type (e.g., push, pull_request)
  workspaces:
    - name: shared-workspace

  tasks:
    - name: show-params
      description: "Show the parameters received by the pipeline"
      taskRef:
        name: show-params-task
      params:
        - name: redhat-base-image
          value: $(params.redhat-base-image)
        - name: repository-url
          value: $(params.repository-url)
        - name: revision
          value: $(params.revision)
        - name: ref
          value: $(params.ref)
        - name: event-type
          value: $(params.event-type)

    - name: git-clone
      description: "Clone the git repository"
      runAfter:
        - show-params
      when:
        - input: $(params.event-type)
          operator: in
          values: ["pull_request"]
      taskRef:
        name: git-clone-task
      params:
        - name: redhat-base-image
          value: $(params.redhat-base-image)
        - name: repository-url
          value: $(params.repository-url)
        - name: revision
          value: $(params.revision)
      workspaces:
        - name: output
          workspace: shared-workspace

    - name: lint
      description: "Run linting on the source code"
      runAfter: 
        - git-clone
      when:
        - input: $(params.event-type)
          operator: in
          values: ["pull_request"]
      taskRef: 
        name: lint-task
      params:
        - name: python
          value: $(params.python)
        - name: repository-url
          value: $(params.repository-url)
      workspaces:
        - name: source
          workspace: shared-workspace

    - name: deploy
      description: "Deploy the application (only on push to main branch)"
      runAfter:
        - show-params
      when:
        - input: $(params.event-type)
          operator: in
          values: ["push"]
        - input: $(params.ref)
          operator: in
          values: ["refs/heads/main"]
      taskRef:
        name: deploy-task
      params:
        - name: redhat-base-image
          value: $(params.redhat-base-image)
      workspaces:
        - name: source
          workspace: shared-workspace

