apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: show-params-task
spec:
  params:
    - name: repository-url
    - name: revision
    - name: ref
    - name: event-type
  steps:
    - name: echo-params
      image: registry.access.redhat.com/ubi9/ubi:latest
      script: |
        #!/bin/bash
        echo ">>> [SHOW PARAMS] with RedHat image"
        echo "repository-url=$(params.repository-url)"
        echo "revision=$(params.revision)"
        echo "ref=$(params.ref)"
        echo "event-type=$(params.event-type)"

---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: git-clone-task
spec:
  params:
    - name: url
    - name: rev
  workspaces:
    - name: output
  steps:
    - name: echo-clone
      image: registry.access.redhat.com/ubi9/ubi:latest
      workingDir: $(workspaces.output.path)
      script: |
        #!/bin/bash
        echo ">>> [GIT CLONE DUMMY] with RedHat image"
        echo "URL=$(params.url)"
        echo "REV=$(params.rev)"
        echo "TARGET=$(workspaces.output.path)/source"

---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: lint-task
spec:
  params:
    - name: repository-url
  workspaces:
    - name: source
  steps:
    - name: run-lint
      image: registry.access.redhat.com/ubi9/python-312-minimal
      workingDir: $(workspaces.source.path)
      script: |
        #!/bin/bash
        echo ">>> [LINT DUMMY] with Python 3.11"
        echo "Repo=$(params.repository-url)"
        echo "Workspace=$(workspaces.source.path)"

---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: deploy-task
spec:
  workspaces:
    - name: source
  steps:
    - name: echo-deploy
      image: registry.access.redhat.com/ubi9/ubi:latest
      workingDir: $(workspaces.source.path)
      script: |
        #!/bin/bash
        echo ">>> [DEPLOY DUMMY] running for push to refs/heads/main with RedHat image"
