apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: show-params-task
spec:
  params:
    - name: redhat-base-image
    - name: repository-url
    - name: revision
    - name: ref
    - name: event-type
  steps:
    - name: echo-params
      image: $(params.redhat-base-image)
      script: |
        #!/bin/bash
        make show-params

---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: git-clone-task
spec:
  workspaces:
    - name: output
  params:
    - name: redhat-base-image
    - name: repository-url
    - name: revision
  steps:
    - name: echo-clone
      image: $(params.redhat-base-image)
      workingDir: $(workspaces.output.path)
      env:
        - name: repository-url
          value: $(params.repository-url)
        - name: revision
          value: $(params.revision)
        - name: target
          value: $(workspaces.output.path)/source
      script: |
        #!/bin/bash
        make git-clone

---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: lint-task
spec:
  workspaces:
    - name: source
  params:
    - name: python
    - name: repository-url
  steps:
    - name: install-dependencies
      image: $(params.python)
      workingDir: $(workspaces.source.path)
      env:
        - name: repo
          value: $(params.repository-url)
      script: |
        #!/bin/bash
        pip3 install -r requirements.txt

    - name: run-lint
      image: $(params.python)
      workingDir: $(workspaces.source.path)
      script: |
        #!/bin/bash
        make lint

---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: deploy-task
spec:
  workspaces:
    - name: source
  params:
    - name: redhat-base-image
  steps:
    - name: echo-deploy
      image: $(params.redhat-base-image)
      workingDir: $(workspaces.source.path)
      script: |
        #!/bin/bash
        make deploy
