apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: git-clone-task
spec:
  workspaces:
    - name: output
  params:
    - name: redhat-base-image
    - name: repository-url
    - name: revision
  steps:
    - name: echo-clone
      image: $(params.redhat-base-image)
      workingDir: $(workspaces.output.path)
      env:
        - name: repository_url
          value: $(params.repository-url)
        - name: revision
          value: $(params.revision)
        - name: target
          value: $(workspaces.output.path)/source
      script: |
        #!/bin/bash
        set -e
        echo "Installing git..."
        dnf install -y git
        echo "Cloning the repository..."
        echo "Repository: $repository_url"
        echo "Revision: $revision"
        mkdir -p "$target"
        git clone --branch "$revision" "$repository_url" "$target"

---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: lint-task
spec:
  workspaces:
    - name: output
  params:
    - name: redhat-base-image
    - name: python
    - name: repository-url
  steps:
    - name: install-make
      image: $(params.redhat-base-image)
      workingDir: $(workspaces.output.path)/source
      script: |
        #!/bin/bash
        echo "Installing make..."
        dnf install -y make

    - name: lint
      image: $(params.python)
      workingDir: $(workspaces.output.path)/source
      env:
        - name: repository_url
          value: $(params.repository-url)
        - name: workspace
          value: $(workspaces.output.path)/source
      script: |
        #!/bin/bash
        set -e
        echo "Installing dependencies..."
        pip3 install -r requirements.txt
        echo "Running linting on the repository..."
        make lint

---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: deploy-task
spec:
  workspaces:
    - name: output
  params:
    - name: redhat-base-image
  steps:
    - name: echo-deploy
      image: $(params.redhat-base-image)
      workingDir: $(workspaces.output.path)/source
      script: |
        #!/bin/bash
        make deploy
