apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: git-clone-task
spec:
  workspaces:
    - name: output
  params:
    - name: redhat-base-image
    - name: repository-url
    - name: revision
  steps:
    - name: echo-clone
      image: $(params.redhat-base-image)
      workingDir: $(workspaces.output.path)
      env:
        - name: repository-url
          value: $(params.repository-url)
        - name: revision
          value: $(params.revision)
        - name: target
          value: $(workspaces.output.path)/source
      script: |
        #!/bin/bash
        set -e
        echo "Installing git..."
        dnf install -y git
        echo "Cloning the repository..."
        echo "Repository: $repository-url"
        echo "Revision: $revision"
        git clone --branch "￼revision""repository-url" "$target"

---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: lint-task
spec:
  workspaces:
    - name: source
  params:
    - name: redhat-base-image
    - name: python
    - name: repository-url
  steps:
    - name: install-dependencies
      image: $(params.python)
      workingDir: $(workspaces.source.path)
      env:
        - name: repo
          value: $(params.repository-url)
      script: |
        #!/bin/bash
        pip3 install -r requirements.txt

    - name: install-make
      image: $(params.redhat-base-image)
      workingDir: $(workspaces.source.path)
      script: |
        #!/bin/bash
        dnf install -y make

    - name: run-lint
      image: $(params.python)
      workingDir: $(workspaces.source.path)
      script: |
        #!/bin/bash
        export repository_url="$repository_url"
        export workspace="$workspace"
        make lint

---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: deploy-task
spec:
  workspaces:
    - name: source
  params:
    - name: redhat-base-image
  steps:
    - name: echo-deploy
      image: $(params.redhat-base-image)
      workingDir: $(workspaces.source.path)
      script: |
        #!/bin/bash
        make deploy
